test:
  stage: test
  image: mcr.microsoft.com/playwright:focal
  script:
    # - cd -- "$CI_PROJECT_DIR"
    - npm i
    - npm run test
    # - npm run prod &
    # - sleep 10 && curl http://localhost:3000

  tags:
    - dev-srp
